### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by mchernyavsky**

### CODE REVIEW

**Comment by xamgore** [comment]
Hey, why don't you put an `.editorconfig` or IDEA formatting config files (inside `.idea` folder) here?

**Comment by valis** [comment]
Auto formatting makes things worse.

**Comment by valis** [comment]
> Hey, why don't you put an `.editorconfig` or IDEA formatting config files (inside `.idea` folder) here?

Different users might have different configs. The only common part is probably the indent size. So, I don't see the point. It is easier to set it manually.

**Comment by xamgore** [comment]
@valis, I don't really understand, how contributors can have different indent styles (spaces / tabs) or indent size (2 / 4 / 8 spaces) in the same project. That's why `.editorconfig` standard was created.

Anyway, if you don't want to add `.idea` folder to the project, think about a support of the new official coding conventions. That can be done by [modifying `.gradle`](https://blog.jetbrains.com/kotlin/2018/09/kotlin-1-3-rc-is-here-migrate-your-coroutines/#Code+style) file.

**Pull request closed without merging**
