### PR TITLE
Add "Swap infix operator arguments" intention (#44)

### PR DESCRIPTION
**Pull request by mmagic-boy**

### CODE REVIEW

**Comment by ice1000** [comment]
@octomarat Did you configure your git username intentionally to not match your GitHub account?

**Comment by octomarat** [comment]
No, but I do not remember how that happened)

**Comment by ice1000** [comment]
image
Just wanna say that this commit is not recognized by github as done by you. You can use `git log` at cli to inspect the email you used -- it should match your github email

**Comment by octomarat** [comment]
Right, I have many emails, configured them all in my account. Thanks for noticing)

**Comment by ice1000** [comment]
You are welcome :)

**Pull request merged**
